# https://taskfile.dev

version: "3"

vars:
  PACKAGES:
    [
      ansi,
      cellbuf,
      colors,
      conpty,
      editor,
      errors,
      examples,
      exp/golden,
      exp/higherorder,
      exp/maps,
      exp/open,
      exp/ordered,
      exp/slice,
      exp/strings,
      exp/teatest,
      exp/teatest/v2,
      input,
      json,
      sshkey,
      term,
      termios,
      vt,
      wcwidth,
      windows,
      xpty,
    ]

tasks:
  fmt:
    desc: Run gofumpt for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && gofmt -s -w .

  modernize:
    desc: Run gofumpt for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && modernize -fix ./...

  lint:
    desc: Run base linters for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && golangci-lint run

  test:
    desc: Run tests for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && go test ./... {{.CLI_ARGS}}
