// Code generated by internal/gen. DO NOT EDIT.

package ansi

import (
	"fmt"
	"io"
	"strings"
)

// WriteCursorBackward writes the sequence to the writer.
//
// Cursor Backward (CUB) moves the cursor back (left) a specified number of
// columns in the same line. The cursor stops at the left margin.
//
// See: https://vt100.net/docs/vt510-rm/CUB.html
func WriteCursorBackward(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[D")
	}

	return fmt.Fprintf(w, "\x1b[%dD", n)
}

// WriteCUB writes the sequence to the writer.
//
// Cursor Backward (CUB) moves the cursor back (left) a specified number of
// columns in the same line. The cursor stops at the left margin.
//
// See: https://vt100.net/docs/vt510-rm/CUB.html
func WriteCUB(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[D")
	}

	return fmt.Fprintf(w, "\x1b[%dD", n)
}

// CursorBackward formats the sequence into a string.
//
// Cursor Backward (CUB) moves the cursor back (left) a specified number of
// columns in the same line. The cursor stops at the left margin.
//
// See: https://vt100.net/docs/vt510-rm/CUB.html
func CursorBackward(n int) string {
	var b strings.Builder
	WriteCursorBackward(&b, n)
	return b.String()
}

// CUB formats the sequence into a string.
//
// Cursor Backward (CUB) moves the cursor back (left) a specified number of
// columns in the same line. The cursor stops at the left margin.
//
// See: https://vt100.net/docs/vt510-rm/CUB.html
func CUB(n int) string {
	var b strings.Builder
	WriteCUB(&b, n)
	return b.String()
}

// WriteCursorDown writes the sequence to the writer.
//
// Cursor Down (CUD) moves the cursor down a specified number of lines in the
// same column. The cursor stops at the bottom margin. If the cursor is already
// below the bottom margin, then the cursor stops at the bottom line.
//
//	CSI n B
//
// See: https://vt100.net/docs/vt510-rm/CUD.html
func WriteCursorDown(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[B")
	}

	return fmt.Fprintf(w, "\x1b[%dB", n)
}

// WriteCUD writes the sequence to the writer.
//
// Cursor Down (CUD) moves the cursor down a specified number of lines in the
// same column. The cursor stops at the bottom margin. If the cursor is already
// below the bottom margin, then the cursor stops at the bottom line.
//
//	CSI n B
//
// See: https://vt100.net/docs/vt510-rm/CUD.html
func WriteCUD(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[B")
	}

	return fmt.Fprintf(w, "\x1b[%dB", n)
}

// CursorDown formats the sequence into a string.
//
// Cursor Down (CUD) moves the cursor down a specified number of lines in the
// same column. The cursor stops at the bottom margin. If the cursor is already
// below the bottom margin, then the cursor stops at the bottom line.
//
//	CSI n B
//
// See: https://vt100.net/docs/vt510-rm/CUD.html
func CursorDown(n int) string {
	var b strings.Builder
	WriteCursorDown(&b, n)
	return b.String()
}

// CUD formats the sequence into a string.
//
// Cursor Down (CUD) moves the cursor down a specified number of lines in the
// same column. The cursor stops at the bottom margin. If the cursor is already
// below the bottom margin, then the cursor stops at the bottom line.
//
//	CSI n B
//
// See: https://vt100.net/docs/vt510-rm/CUD.html
func CUD(n int) string {
	var b strings.Builder
	WriteCUD(&b, n)
	return b.String()
}

// CUD1 moves the cursor down one cell.
const CUD1 = "\x1b[B"

// WriteCursorForward writes the sequence to the writer.
//
// Cursor Forward (CUF) moves the cursor forward (right) a specified number of
// columns in the same line. The cursor stops at the right margin.
//
// See: https://vt100.net/docs/vt510-rm/CUF.html
func WriteCursorForward(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[C")
	}

	return fmt.Fprintf(w, "\x1b[%dC", n)
}

// WriteCUF writes the sequence to the writer.
//
// Cursor Forward (CUF) moves the cursor forward (right) a specified number of
// columns in the same line. The cursor stops at the right margin.
//
// See: https://vt100.net/docs/vt510-rm/CUF.html
func WriteCUF(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[C")
	}

	return fmt.Fprintf(w, "\x1b[%dC", n)
}

// CursorForward formats the sequence into a string.
//
// Cursor Forward (CUF) moves the cursor forward (right) a specified number of
// columns in the same line. The cursor stops at the right margin.
//
// See: https://vt100.net/docs/vt510-rm/CUF.html
func CursorForward(n int) string {
	var b strings.Builder
	WriteCursorForward(&b, n)
	return b.String()
}

// CUF formats the sequence into a string.
//
// Cursor Forward (CUF) moves the cursor forward (right) a specified number of
// columns in the same line. The cursor stops at the right margin.
//
// See: https://vt100.net/docs/vt510-rm/CUF.html
func CUF(n int) string {
	var b strings.Builder
	WriteCUF(&b, n)
	return b.String()
}

// WriteCursorHorizontalAbsolute writes the sequence to the writer.
//
// Cursor Horizontal Absolute (CHA) moves the cursor to the specified column
// in the current line.
//
// See: https://vt100.net/docs/vt510-rm/CHA.html
func WriteCursorHorizontalAbsolute(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[G")
	}

	return fmt.Fprintf(w, "\x1b[%dG", n)
}

// WriteCHA writes the sequence to the writer.
//
// Cursor Horizontal Absolute (CHA) moves the cursor to the specified column
// in the current line.
//
// See: https://vt100.net/docs/vt510-rm/CHA.html
func WriteCHA(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[G")
	}

	return fmt.Fprintf(w, "\x1b[%dG", n)
}

// CursorHorizontalAbsolute formats the sequence into a string.
//
// Cursor Horizontal Absolute (CHA) moves the cursor to the specified column
// in the current line.
//
// See: https://vt100.net/docs/vt510-rm/CHA.html
func CursorHorizontalAbsolute(n int) string {
	var b strings.Builder
	WriteCursorHorizontalAbsolute(&b, n)
	return b.String()
}

// CHA formats the sequence into a string.
//
// Cursor Horizontal Absolute (CHA) moves the cursor to the specified column
// in the current line.
//
// See: https://vt100.net/docs/vt510-rm/CHA.html
func CHA(n int) string {
	var b strings.Builder
	WriteCHA(&b, n)
	return b.String()
}

// WriteCursorNextLine writes the sequence to the writer.
//
// Cursor Next Line (CNL) moves the cursor to the first column of the next line,
// n lines down.
//
// See: https://vt100.net/docs/vt510-rm/CNL.html
func WriteCursorNextLine(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[E")
	}

	return fmt.Fprintf(w, "\x1b[%dE", n)
}

// WriteCNL writes the sequence to the writer.
//
// Cursor Next Line (CNL) moves the cursor to the first column of the next line,
// n lines down.
//
// See: https://vt100.net/docs/vt510-rm/CNL.html
func WriteCNL(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[E")
	}

	return fmt.Fprintf(w, "\x1b[%dE", n)
}

// CursorNextLine formats the sequence into a string.
//
// Cursor Next Line (CNL) moves the cursor to the first column of the next line,
// n lines down.
//
// See: https://vt100.net/docs/vt510-rm/CNL.html
func CursorNextLine(n int) string {
	var b strings.Builder
	WriteCursorNextLine(&b, n)
	return b.String()
}

// CNL formats the sequence into a string.
//
// Cursor Next Line (CNL) moves the cursor to the first column of the next line,
// n lines down.
//
// See: https://vt100.net/docs/vt510-rm/CNL.html
func CNL(n int) string {
	var b strings.Builder
	WriteCNL(&b, n)
	return b.String()
}

// WriteCursorPosition writes the sequence to the writer.
//
// Cursor Position (CUP) moves the cursor to the specified line and column.
// The starting point for lines and columns depends on the setting of origin
// mode (DECOM). CUP applies only to the current page.
//
// Default is 1,1.
//
//	CSI n ; m H
//
// See: https://vt100.net/docs/vt510-rm/CUP.html
func WriteCursorPosition(w io.Writer, row int, col int) (int, error) {
	if row <= 1 && col <= 1 {
		return io.WriteString(w, "\x1b[H")
	}

	if row > 1 && col > 1 {
		return fmt.Fprintf(w, "\x1b[%d;%dH", row, col)
	} else if row <= 1 && col > 1 {
		return fmt.Fprintf(w, "\x1b[%dH", col)
	} else if row > 1 && col <= 1 {
		return fmt.Fprintf(w, "\x1b[%dH", row)
	}
	return io.WriteString(w, "\x1b[H")
}

// WriteCUP writes the sequence to the writer.
//
// Cursor Position (CUP) moves the cursor to the specified line and column.
// The starting point for lines and columns depends on the setting of origin
// mode (DECOM). CUP applies only to the current page.
//
// Default is 1,1.
//
//	CSI n ; m H
//
// See: https://vt100.net/docs/vt510-rm/CUP.html
func WriteCUP(w io.Writer, row int, col int) (int, error) {
	if row <= 1 && col <= 1 {
		return io.WriteString(w, "\x1b[H")
	}

	if row > 1 && col > 1 {
		return fmt.Fprintf(w, "\x1b[%d;%dH", row, col)
	} else if row <= 1 && col > 1 {
		return fmt.Fprintf(w, "\x1b[%dH", col)
	} else if row > 1 && col <= 1 {
		return fmt.Fprintf(w, "\x1b[%dH", row)
	}
	return io.WriteString(w, "\x1b[H")
}

// CursorPosition formats the sequence into a string.
//
// Cursor Position (CUP) moves the cursor to the specified line and column.
// The starting point for lines and columns depends on the setting of origin
// mode (DECOM). CUP applies only to the current page.
//
// Default is 1,1.
//
//	CSI n ; m H
//
// See: https://vt100.net/docs/vt510-rm/CUP.html
func CursorPosition(row int, col int) string {
	var b strings.Builder
	WriteCursorPosition(&b, row, col)
	return b.String()
}

// CUP formats the sequence into a string.
//
// Cursor Position (CUP) moves the cursor to the specified line and column.
// The starting point for lines and columns depends on the setting of origin
// mode (DECOM). CUP applies only to the current page.
//
// Default is 1,1.
//
//	CSI n ; m H
//
// See: https://vt100.net/docs/vt510-rm/CUP.html
func CUP(row int, col int) string {
	var b strings.Builder
	WriteCUP(&b, row, col)
	return b.String()
}

// CursorHomePosition moves the cursor to the upper left corner.
const CursorHomePosition = "\x1b[H"

// WriteCursorPreviousLine writes the sequence to the writer.
//
// Cursor Previous Line (CPL) moves the cursor to the first column of the
// previous line, n lines up.
//
// See: https://vt100.net/docs/vt510-rm/CPL.html
func WriteCursorPreviousLine(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[F")
	}

	return fmt.Fprintf(w, "\x1b[%dF", n)
}

// WriteCPL writes the sequence to the writer.
//
// Cursor Previous Line (CPL) moves the cursor to the first column of the
// previous line, n lines up.
//
// See: https://vt100.net/docs/vt510-rm/CPL.html
func WriteCPL(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[F")
	}

	return fmt.Fprintf(w, "\x1b[%dF", n)
}

// CursorPreviousLine formats the sequence into a string.
//
// Cursor Previous Line (CPL) moves the cursor to the first column of the
// previous line, n lines up.
//
// See: https://vt100.net/docs/vt510-rm/CPL.html
func CursorPreviousLine(n int) string {
	var b strings.Builder
	WriteCursorPreviousLine(&b, n)
	return b.String()
}

// CPL formats the sequence into a string.
//
// Cursor Previous Line (CPL) moves the cursor to the first column of the
// previous line, n lines up.
//
// See: https://vt100.net/docs/vt510-rm/CPL.html
func CPL(n int) string {
	var b strings.Builder
	WriteCPL(&b, n)
	return b.String()
}

// WriteCursorUp writes the sequence to the writer.
//
// Cursor Up (CUU) moves the cursor up a specified number of lines in the same
// column. The cursor stops at the top margin. If the cursor is already above
// the top margin, then the cursor stops at the top line.
//
//	CSI n A
//
// See: https://vt100.net/docs/vt510-rm/CUU.html
func WriteCursorUp(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[A")
	}

	return fmt.Fprintf(w, "\x1b[%dA", n)
}

// WriteCUU writes the sequence to the writer.
//
// Cursor Up (CUU) moves the cursor up a specified number of lines in the same
// column. The cursor stops at the top margin. If the cursor is already above
// the top margin, then the cursor stops at the top line.
//
//	CSI n A
//
// See: https://vt100.net/docs/vt510-rm/CUU.html
func WriteCUU(w io.Writer, n int) (int, error) {
	if n <= 1 {
		return io.WriteString(w, "\x1b[A")
	}

	return fmt.Fprintf(w, "\x1b[%dA", n)
}

// CursorUp formats the sequence into a string.
//
// Cursor Up (CUU) moves the cursor up a specified number of lines in the same
// column. The cursor stops at the top margin. If the cursor is already above
// the top margin, then the cursor stops at the top line.
//
//	CSI n A
//
// See: https://vt100.net/docs/vt510-rm/CUU.html
func CursorUp(n int) string {
	var b strings.Builder
	WriteCursorUp(&b, n)
	return b.String()
}

// CUU formats the sequence into a string.
//
// Cursor Up (CUU) moves the cursor up a specified number of lines in the same
// column. The cursor stops at the top margin. If the cursor is already above
// the top margin, then the cursor stops at the top line.
//
//	CSI n A
//
// See: https://vt100.net/docs/vt510-rm/CUU.html
func CUU(n int) string {
	var b strings.Builder
	WriteCUU(&b, n)
	return b.String()
}

// CUU1 moves the cursor up one cell.
const CUU1 = "\x1b[A"

// Index is an ANSI escape sequence.
//
// Index (IND) moves the cursor down one line in the same column.
//
// If the cursor is at the bottom margin, the screen scrolls up.
//
//	ESC D
//
// See: https://vt100.net/docs/vt510-rm/IND.html
const Index = "\x1bD"

// RequestBackgroundColor is an ANSI escape sequence.
//
// Request Background Color requests the current default terminal background
// color.
//
//	OSC 11 ; ? BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const RequestBackgroundColor = "\x1b]11;?\a"

// RequestCursorColor is an ANSI escape sequence.
//
// Request Cursor Color requests the current terminal cursor color.
//
//	OSC 12 ; ? BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const RequestCursorColor = "\x1b]12;?\a"

// RequestForegroundColor is an ANSI escape sequence.
//
// Request Foreground Color requests the current default terminal foreground
// color.
//
//	OSC 10 ; ? BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const RequestForegroundColor = "\x1b]10;?\a"

// RequestNameVersion is an ANSI escape sequence.
//
// Request Name Version (XTVERSION) requests the terminal's name and version.
//
// The terminal responds with a DSR sequence identifying the terminal:
//
//	DCS > | text ST
//
//	CSI > 0 q
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-PC-Style-Function-Keys
const RequestNameVersion = "\x1b[>q"

// XTVERSION is an ANSI escape sequence.
//
// Request Name Version (XTVERSION) requests the terminal's name and version.
//
// The terminal responds with a DSR sequence identifying the terminal:
//
//	DCS > | text ST
//
//	CSI > 0 q
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-PC-Style-Function-Keys
const XTVERSION = "\x1b[>q"

// RequestPrimaryClipboard is an ANSI escape sequence.
//
// Request Primary Clipboard requests the primary clipboard.
//
//	OSC 52 ; p ; ? BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const RequestPrimaryClipboard = "\x1b]52;p;?\a"

// RequestPrimaryDeviceAttributes is an ANSI escape sequence.
//
// Request Primary Device Attributes (DA1) requests the terminal's primary
// device attributes.
//
// The terminal responds with:
//
//	CSI ? Ps ; ... c
//
// Common attributes include:
// - 1: 132 columns
// - 2: Printer port
// - 4: Sixel
// - 6: Selective erase
// - 7: Soft character set (DRCS)
// - 8: User-defined keys (UDKs)
// - 9: National replacement character sets (NRCS)
// - 15: Technical character set
// - 18: Windowing capability
// - 21: Horizontal scrolling
//
//	CSI c
//
// See: https://vt100.net/docs/vt510-rm/DA1.html
const RequestPrimaryDeviceAttributes = "\x1b[c"

// DA1 is an ANSI escape sequence.
//
// Request Primary Device Attributes (DA1) requests the terminal's primary
// device attributes.
//
// The terminal responds with:
//
//	CSI ? Ps ; ... c
//
// Common attributes include:
// - 1: 132 columns
// - 2: Printer port
// - 4: Sixel
// - 6: Selective erase
// - 7: Soft character set (DRCS)
// - 8: User-defined keys (UDKs)
// - 9: National replacement character sets (NRCS)
// - 15: Technical character set
// - 18: Windowing capability
// - 21: Horizontal scrolling
//
//	CSI c
//
// See: https://vt100.net/docs/vt510-rm/DA1.html
const DA1 = "\x1b[c"

// RequestSecondaryDeviceAttributes is an ANSI escape sequence.
//
// Request Secondary Device Attributes (DA2) requests the terminal's secondary
// device attributes.
//
// The terminal responds with:
//
//	CSI > Ps ; ... c
//
//	CSI > c
//
// See: https://vt100.net/docs/vt510-rm/DA2.html
const RequestSecondaryDeviceAttributes = "\x1b[>c"

// DA2 is an ANSI escape sequence.
//
// Request Secondary Device Attributes (DA2) requests the terminal's secondary
// device attributes.
//
// The terminal responds with:
//
//	CSI > Ps ; ... c
//
//	CSI > c
//
// See: https://vt100.net/docs/vt510-rm/DA2.html
const DA2 = "\x1b[>c"

// RequestSystemClipboard is an ANSI escape sequence.
//
// Request System Clipboard requests the system clipboard.
//
//	OSC 52 ; c ; ? BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const RequestSystemClipboard = "\x1b]52c;?\a"

// RequestTertiaryDeviceAttributes is an ANSI escape sequence.
//
// Request Tertiary Device Attributes (DA3) requests the terminal's tertiary
// device attributes.
//
// The terminal responds with:
//
//	DCS ! | Text ST
//
// Where Text is the unit ID for the terminal.
//
//	CSI = c
//
// See: https://vt100.net/docs/vt510-rm/DA3.html
const RequestTertiaryDeviceAttributes = "\x1b[=c"

// DA3 is an ANSI escape sequence.
//
// Request Tertiary Device Attributes (DA3) requests the terminal's tertiary
// device attributes.
//
// The terminal responds with:
//
//	DCS ! | Text ST
//
// Where Text is the unit ID for the terminal.
//
//	CSI = c
//
// See: https://vt100.net/docs/vt510-rm/DA3.html
const DA3 = "\x1b[=c"

// ResetBackgroundColor is an ANSI escape sequence.
//
// Reset Background Color resets the default terminal background color.
//
//	OSC 111 BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const ResetBackgroundColor = "\x1b]111\a"

// ResetCursorColor is an ANSI escape sequence.
//
// Reset Cursor Color resets the terminal cursor color.
//
//	OSC 112 BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const ResetCursorColor = "\x1b]112\a"

// ResetForegroundColor is an ANSI escape sequence.
//
// Reset Foreground Color resets the default terminal foreground color.
//
//	OSC 110 BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const ResetForegroundColor = "\x1b]110\a"

// ResetPrimaryClipboard is an ANSI escape sequence.
//
// Reset Primary Clipboard resets the primary clipboard.
//
//	OSC 52 ; p ; BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const ResetPrimaryClipboard = "\x1b]52;p;\a"

// ResetSystemClipboard is an ANSI escape sequence.
//
// Reset System Clipboard resets the system clipboard.
//
//	OSC 52 ; c ; BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
const ResetSystemClipboard = "\x1b]52c;\a"

// RestoreCursor is an ANSI escape sequence.
//
// Restore Cursor (DECRC) restores the terminal to the state saved by the
// save cursor (DECSC) function.
//
// If nothing was saved by DECSC, it moves the cursor to the home position,
// resets origin mode (DECOM), turns all character attributes off, and maps
// the ASCII character set into GL and the DEC Supplemental Graphic set into GR.
//
//	ESC 8
//
// See: https://vt100.net/docs/vt510-rm/DECRC.html
const RestoreCursor = "\x1b8"

// DECRC is an ANSI escape sequence.
//
// Restore Cursor (DECRC) restores the terminal to the state saved by the
// save cursor (DECSC) function.
//
// If nothing was saved by DECSC, it moves the cursor to the home position,
// resets origin mode (DECOM), turns all character attributes off, and maps
// the ASCII character set into GL and the DEC Supplemental Graphic set into GR.
//
//	ESC 8
//
// See: https://vt100.net/docs/vt510-rm/DECRC.html
const DECRC = "\x1b8"

// RestoreCurrentCursorPosition is an ANSI escape sequence.
//
// Restore Current Cursor Position (SCORC) moves the cursor to a previously
// saved position within the current page.
//
//	CSI u
//
// See: https://vt100.net/docs/vt510-rm/SCORC.html
const RestoreCurrentCursorPosition = "\x1b[u"

// SCORC is an ANSI escape sequence.
//
// Restore Current Cursor Position (SCORC) moves the cursor to a previously
// saved position within the current page.
//
//	CSI u
//
// See: https://vt100.net/docs/vt510-rm/SCORC.html
const SCORC = "\x1b[u"

// ReverseIndex is an ANSI escape sequence.
//
// Reverse Index (RI) moves the cursor up one line in the same column.
//
// If the cursor is at the top margin, the screen scrolls down.
//
//	ESC M
//
// See: https://vt100.net/docs/vt510-rm/RI.html
const ReverseIndex = "\x1bM"

// SaveCursor is an ANSI escape sequence.
//
// Save Cursor (DECSC) saves the cursor position and attributes.
//
// DECSC saves the following items in the terminal's memory:
// - Cursor position
// - Character attributes set by the SGR command
// - Character sets (G0, G1, G2, or G3) currently in GL and GR
// - Wrap flag (autowrap or no autowrap)
// - State of origin mode (DECOM)
// - Selective erase attribute
// - Any single shift 2 (SS2) or single shift 3 (SS3) functions sent
//
//	ESC 7
//
// See: https://vt100.net/docs/vt510-rm/DECSC.html
const SaveCursor = "\x1b7"

// DECSC is an ANSI escape sequence.
//
// Save Cursor (DECSC) saves the cursor position and attributes.
//
// DECSC saves the following items in the terminal's memory:
// - Cursor position
// - Character attributes set by the SGR command
// - Character sets (G0, G1, G2, or G3) currently in GL and GR
// - Wrap flag (autowrap or no autowrap)
// - State of origin mode (DECOM)
// - Selective erase attribute
// - Any single shift 2 (SS2) or single shift 3 (SS3) functions sent
//
//	ESC 7
//
// See: https://vt100.net/docs/vt510-rm/DECSC.html
const DECSC = "\x1b7"

// SaveCurrentCursorPosition is an ANSI escape sequence.
//
// Save Current Cursor Position (SCOSC) saves the current cursor position for
// SCO console mode.
//
// It functions identically to the DECSC command, with the exception that it
// does not save the page number where the cursor is located.
//
//	CSI s
//
// See: https://vt100.net/docs/vt510-rm/SCOSC.html
const SaveCurrentCursorPosition = "\x1b[s"

// SCOSC is an ANSI escape sequence.
//
// Save Current Cursor Position (SCOSC) saves the current cursor position for
// SCO console mode.
//
// It functions identically to the DECSC command, with the exception that it
// does not save the page number where the cursor is located.
//
//	CSI s
//
// See: https://vt100.net/docs/vt510-rm/SCOSC.html
const SCOSC = "\x1b[s"

// WriteSelectCharacterSet writes the sequence to the writer.
//
// Select Character Set (SCS) designates character sets to G-sets.
//
// Where gset is the G-set character designator, and charset is the identifier.
//
// For 94-character sets, the designator can be one of:
// - ( G0
// - ) G1
// - * G2
// - + G3
//
// For 96-character sets, the designator can be one of:
// - - G1
// - . G2
// - / G3
//
// Some common 94-character sets are:
// - 0 DEC Special Drawing Set
// - A United Kingdom (UK)
// - B United States (USASCII)
//
//	ESC Ps Pd
//
// See: https://vt100.net/docs/vt510-rm/SCS.html
func WriteSelectCharacterSet(w io.Writer, gset byte, charset byte) (int, error) {
	return fmt.Fprintf(w, "\x1b%c%c", gset, charset)
}

// WriteSCS writes the sequence to the writer.
//
// Select Character Set (SCS) designates character sets to G-sets.
//
// Where gset is the G-set character designator, and charset is the identifier.
//
// For 94-character sets, the designator can be one of:
// - ( G0
// - ) G1
// - * G2
// - + G3
//
// For 96-character sets, the designator can be one of:
// - - G1
// - . G2
// - / G3
//
// Some common 94-character sets are:
// - 0 DEC Special Drawing Set
// - A United Kingdom (UK)
// - B United States (USASCII)
//
//	ESC Ps Pd
//
// See: https://vt100.net/docs/vt510-rm/SCS.html
func WriteSCS(w io.Writer, gset byte, charset byte) (int, error) {
	return fmt.Fprintf(w, "\x1b%c%c", gset, charset)
}

// SelectCharacterSet formats the sequence into a string.
//
// Select Character Set (SCS) designates character sets to G-sets.
//
// Where gset is the G-set character designator, and charset is the identifier.
//
// For 94-character sets, the designator can be one of:
// - ( G0
// - ) G1
// - * G2
// - + G3
//
// For 96-character sets, the designator can be one of:
// - - G1
// - . G2
// - / G3
//
// Some common 94-character sets are:
// - 0 DEC Special Drawing Set
// - A United Kingdom (UK)
// - B United States (USASCII)
//
//	ESC Ps Pd
//
// See: https://vt100.net/docs/vt510-rm/SCS.html
func SelectCharacterSet(gset byte, charset byte) string {
	var b strings.Builder
	WriteSelectCharacterSet(&b, gset, charset)
	return b.String()
}

// SCS formats the sequence into a string.
//
// Select Character Set (SCS) designates character sets to G-sets.
//
// Where gset is the G-set character designator, and charset is the identifier.
//
// For 94-character sets, the designator can be one of:
// - ( G0
// - ) G1
// - * G2
// - + G3
//
// For 96-character sets, the designator can be one of:
// - - G1
// - . G2
// - / G3
//
// Some common 94-character sets are:
// - 0 DEC Special Drawing Set
// - A United Kingdom (UK)
// - B United States (USASCII)
//
//	ESC Ps Pd
//
// See: https://vt100.net/docs/vt510-rm/SCS.html
func SCS(gset byte, charset byte) string {
	var b strings.Builder
	WriteSCS(&b, gset, charset)
	return b.String()
}

// WriteSetBackgroundColor writes the sequence to the writer.
//
// Set Background Color sets the default terminal background color.
//
// Where color is the encoded color number. Most terminals support hex,
// XParseColor rgb: and rgba: strings.
//
//	OSC 11 ; color ST
//	OSC 11 ; color BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
func WriteSetBackgroundColor(w io.Writer, color string) (int, error) {
	return fmt.Fprintf(w, "\x1b]11;%s\a", color)
}

// SetBackgroundColor formats the sequence into a string.
//
// Set Background Color sets the default terminal background color.
//
// Where color is the encoded color number. Most terminals support hex,
// XParseColor rgb: and rgba: strings.
//
//	OSC 11 ; color ST
//	OSC 11 ; color BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
func SetBackgroundColor(color string) string {
	var b strings.Builder
	WriteSetBackgroundColor(&b, color)
	return b.String()
}

// WriteSetCursorColor writes the sequence to the writer.
//
// Set Cursor Color sets the terminal cursor color.
//
// Where color is the encoded color number. Most terminals support hex,
// XParseColor rgb: and rgba: strings.
//
//	OSC 12 ; color ST
//	OSC 12 ; color BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
func WriteSetCursorColor(w io.Writer, color string) (int, error) {
	return fmt.Fprintf(w, "\x1b]12;%s\a", color)
}

// SetCursorColor formats the sequence into a string.
//
// Set Cursor Color sets the terminal cursor color.
//
// Where color is the encoded color number. Most terminals support hex,
// XParseColor rgb: and rgba: strings.
//
//	OSC 12 ; color ST
//	OSC 12 ; color BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
func SetCursorColor(color string) string {
	var b strings.Builder
	WriteSetCursorColor(&b, color)
	return b.String()
}

// WriteSetCursorStyle writes the sequence to the writer.
//
// Set Cursor Style (DECSCUSR) changes the cursor style.
//
// Default is 0.
//
//	CSI Ps SP q
//
// Where Ps is the cursor style:
//
//	0: Blinking block
//	1: Blinking block (default)
//	2: Steady block
//	3: Blinking underline
//	4: Steady underline
//	5: Blinking bar (xterm)
//	6: Steady bar (xterm)
//
// See: https://vt100.net/docs/vt510-rm/DECSCUSR.html
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps-SP-q.1D81
func WriteSetCursorStyle(w io.Writer, style int) (int, error) {
	if style <= 0 {
		return io.WriteString(w, "\x1b[ q")
	}

	return fmt.Fprintf(w, "\x1b[%d q", style)
}

// WriteDECSCUSR writes the sequence to the writer.
//
// Set Cursor Style (DECSCUSR) changes the cursor style.
//
// Default is 0.
//
//	CSI Ps SP q
//
// Where Ps is the cursor style:
//
//	0: Blinking block
//	1: Blinking block (default)
//	2: Steady block
//	3: Blinking underline
//	4: Steady underline
//	5: Blinking bar (xterm)
//	6: Steady bar (xterm)
//
// See: https://vt100.net/docs/vt510-rm/DECSCUSR.html
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps-SP-q.1D81
func WriteDECSCUSR(w io.Writer, style int) (int, error) {
	if style <= 0 {
		return io.WriteString(w, "\x1b[ q")
	}

	return fmt.Fprintf(w, "\x1b[%d q", style)
}

// SetCursorStyle formats the sequence into a string.
//
// Set Cursor Style (DECSCUSR) changes the cursor style.
//
// Default is 0.
//
//	CSI Ps SP q
//
// Where Ps is the cursor style:
//
//	0: Blinking block
//	1: Blinking block (default)
//	2: Steady block
//	3: Blinking underline
//	4: Steady underline
//	5: Blinking bar (xterm)
//	6: Steady bar (xterm)
//
// See: https://vt100.net/docs/vt510-rm/DECSCUSR.html
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps-SP-q.1D81
func SetCursorStyle(style int) string {
	var b strings.Builder
	WriteSetCursorStyle(&b, style)
	return b.String()
}

// DECSCUSR formats the sequence into a string.
//
// Set Cursor Style (DECSCUSR) changes the cursor style.
//
// Default is 0.
//
//	CSI Ps SP q
//
// Where Ps is the cursor style:
//
//	0: Blinking block
//	1: Blinking block (default)
//	2: Steady block
//	3: Blinking underline
//	4: Steady underline
//	5: Blinking bar (xterm)
//	6: Steady bar (xterm)
//
// See: https://vt100.net/docs/vt510-rm/DECSCUSR.html
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps-SP-q.1D81
func DECSCUSR(style int) string {
	var b strings.Builder
	WriteDECSCUSR(&b, style)
	return b.String()
}

// WriteSetForegroundColor writes the sequence to the writer.
//
// Set Foreground Color sets the default terminal foreground color.
//
// Where color is the encoded color number. Most terminals support hex,
// XParseColor rgb: and rgba: strings.
//
//	OSC 10 ; color ST
//	OSC 10 ; color BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
func WriteSetForegroundColor(w io.Writer, color string) (int, error) {
	return fmt.Fprintf(w, "\x1b]10;%s\a", color)
}

// SetForegroundColor formats the sequence into a string.
//
// Set Foreground Color sets the default terminal foreground color.
//
// Where color is the encoded color number. Most terminals support hex,
// XParseColor rgb: and rgba: strings.
//
//	OSC 10 ; color ST
//	OSC 10 ; color BEL
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
func SetForegroundColor(color string) string {
	var b strings.Builder
	WriteSetForegroundColor(&b, color)
	return b.String()
}

// WriteSetPointerShape writes the sequence to the writer.
//
// Set Pointer Shape changes the mouse pointer cursor shape.
//
// Use "default" for the default pointer shape.
//
//	OSC 22 ; Pt ST
//	OSC 22 ; Pt BEL
//
// Where Pt is the pointer shape name.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands
func WriteSetPointerShape(w io.Writer, shape string) (int, error) {
	return fmt.Fprintf(w, "\x1b]22;%s\a", shape)
}

// SetPointerShape formats the sequence into a string.
//
// Set Pointer Shape changes the mouse pointer cursor shape.
//
// Use "default" for the default pointer shape.
//
//	OSC 22 ; Pt ST
//	OSC 22 ; Pt BEL
//
// Where Pt is the pointer shape name.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands
func SetPointerShape(shape string) string {
	var b strings.Builder
	WriteSetPointerShape(&b, shape)
	return b.String()
}

// LS1R is an ANSI escape sequence.
//
// Locking Shift 1 Right (LS1R) shifts G1 into GR character set.
//
//	ESC ~
//
// See: https://vt100.net/docs/vt510-rm/LS1R.html
const LS1R = "\x1b~"

// LS2 is an ANSI escape sequence.
//
// Locking Shift 2 (LS2) shifts G2 into GL character set.
//
//	ESC n
//
// See: https://vt100.net/docs/vt510-rm/LS2.html
const LS2 = "\x1bn"

// LS2R is an ANSI escape sequence.
//
// Locking Shift 2 Right (LS2R) shifts G2 into GR character set.
//
//	ESC }
//
// See: https://vt100.net/docs/vt510-rm/LS2R.html
const LS2R = "\x1b}"

// LS3 is an ANSI escape sequence.
//
// Locking Shift 3 (LS3) shifts G3 into GL character set.
//
//	ESC o
//
// See: https://vt100.net/docs/vt510-rm/LS3.html
const LS3 = "\x1bo"

// LS3R is an ANSI escape sequence.
//
// Locking Shift 3 Right (LS3R) shifts G3 into GR character set.
//
//	ESC |
//
// See: https://vt100.net/docs/vt510-rm/LS3R.html
const LS3R = "\x1b|"

// Keyboard Action Mode (KAM) is a mode that controls locking of the keyboard.
// When the keyboard is locked, it cannot send data to the terminal.
//
// See: https://vt100.net/docs/vt510-rm/KAM.html
const (
	ModeKeyboardAction = ANSIMode(2)
	KAM                = ModeKeyboardAction

	SetModeKeyboardAction     = "\x1b[2h"
	ResetModeKeyboardAction   = "\x1b[2l"
	RequestModeKeyboardAction = "\x1b[2$p"
	SetModeKAM                = SetModeKeyboardAction
	ResetModeKAM              = ResetModeKeyboardAction
	RequestModeKAM            = RequestModeKeyboardAction
)

// Insert/Replace Mode (IRM) is a mode that determines whether characters are
// inserted or replaced when typed.
//
// When enabled, characters are inserted at the cursor position pushing the
// characters to the right. When disabled, characters replace the character at
// the cursor position.
//
// See: https://vt100.net/docs/vt510-rm/IRM.html
const (
	ModeInsertReplace = ANSIMode(4)
	IRM               = ModeInsertReplace

	SetModeInsertReplace     = "\x1b[4h"
	ResetModeInsertReplace   = "\x1b[4l"
	RequestModeInsertReplace = "\x1b[4$p"
	SetModeIRM               = SetModeInsertReplace
	ResetModeIRM             = ResetModeInsertReplace
	RequestModeIRM           = RequestModeInsertReplace
)

// BiDirectional Support Mode (BDSM) is a mode that determines whether the
// terminal supports bidirectional text. When enabled, the terminal supports
// bidirectional text and is set to implicit bidirectional mode. When disabled,
// the terminal does not support bidirectional text.
//
// See ECMA-48 7.2.1.
const (
	ModeBiDirectionalSupport = ANSIMode(8)
	BDSM                     = ModeBiDirectionalSupport

	SetModeBiDirectionalSupport     = "\x1b[8h"
	ResetModeBiDirectionalSupport   = "\x1b[8l"
	RequestModeBiDirectionalSupport = "\x1b[8$p"
	SetModeBDSM                     = SetModeBiDirectionalSupport
	ResetModeBDSM                   = ResetModeBiDirectionalSupport
	RequestModeBDSM                 = RequestModeBiDirectionalSupport
)

// Send Receive Mode (SRM) or Local Echo Mode is a mode that determines whether
// the terminal echoes characters back to the host. When enabled, the terminal
// sends characters to the host as they are typed.
//
// See: https://vt100.net/docs/vt510-rm/SRM.html
const (
	ModeSendReceive = ANSIMode(12)
	SRM             = ModeSendReceive
	LocalEcho       = ModeSendReceive

	SetModeSendReceive     = "\x1b[12h"
	ResetModeSendReceive   = "\x1b[12l"
	RequestModeSendReceive = "\x1b[12$p"
	SetModeSRM             = SetModeSendReceive
	ResetModeSRM           = ResetModeSendReceive
	RequestModeSRM         = RequestModeSendReceive
	SetModeLocalEcho       = SetModeSendReceive
	ResetModeLocalEcho     = ResetModeSendReceive
	RequestModeLocalEcho   = RequestModeSendReceive
)

// Line Feed/New Line Mode (LNM) is a mode that determines whether the terminal
// interprets the line feed character as a new line.
//
// When enabled, the terminal interprets the line feed character as a new line.
// When disabled, the terminal interprets the line feed character as a line feed.
//
// A new line moves the cursor to the first position of the next line.
// A line feed moves the cursor down one line without changing the column
// scrolling the screen if necessary.
//
// See: https://vt100.net/docs/vt510-rm/LNM.html
const (
	ModeLineFeedNewLine = ANSIMode(20)
	LNM                 = ModeLineFeedNewLine

	SetModeLineFeedNewLine     = "\x1b[20h"
	ResetModeLineFeedNewLine   = "\x1b[20l"
	RequestModeLineFeedNewLine = "\x1b[20$p"
	SetModeLNM                 = SetModeLineFeedNewLine
	ResetModeLNM               = ResetModeLineFeedNewLine
	RequestModeLNM             = RequestModeLineFeedNewLine
)

// Cursor Keys Mode (DECCKM) is a mode that determines whether the cursor keys
// send ANSI cursor sequences or application sequences.
//
// See: https://vt100.net/docs/vt510-rm/DECCKM.html
const (
	ModeCursorKeys = DECMode(1)
	DECCKM         = ModeCursorKeys

	SetModeCursorKeys     = "\x1b[?1h"
	ResetModeCursorKeys   = "\x1b[?1l"
	RequestModeCursorKeys = "\x1b[?1$p"
	SetModeDECCKM         = SetModeCursorKeys
	ResetModeDECCKM       = ResetModeCursorKeys
	RequestModeDECCKM     = RequestModeCursorKeys
)

// Origin Mode (DECOM) is a mode that determines whether the cursor moves to the
// home position or the margin position.
//
// See: https://vt100.net/docs/vt510-rm/DECOM.html
const (
	ModeOrigin = DECMode(6)
	DECOM      = ModeOrigin

	SetModeOrigin     = "\x1b[?6h"
	ResetModeOrigin   = "\x1b[?6l"
	RequestModeOrigin = "\x1b[?6$p"
	SetModeDECOM      = SetModeOrigin
	ResetModeDECOM    = ResetModeOrigin
	RequestModeDECOM  = RequestModeOrigin
)

// Auto Wrap Mode (DECAWM) is a mode that determines whether the cursor wraps
// to the next line when it reaches the right margin.
//
// See: https://vt100.net/docs/vt510-rm/DECAWM.html
const (
	ModeAutoWrap = DECMode(7)
	DECAWM       = ModeAutoWrap

	SetModeAutoWrap     = "\x1b[?7h"
	ResetModeAutoWrap   = "\x1b[?7l"
	RequestModeAutoWrap = "\x1b[?7$p"
	SetModeDECAWM       = SetModeAutoWrap
	ResetModeDECAWM     = ResetModeAutoWrap
	RequestModeDECAWM   = RequestModeAutoWrap
)

// X10 Mouse Mode is a mode that determines whether the mouse reports on button
// presses.
//
// The terminal responds with the following encoding:
//
// # CSI M CbCxCy
//
// Where Cb is the button-1, where it can be 1, 2, or 3.
// Cx and Cy are the x and y coordinates of the mouse event.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking
const (
	ModeMouseX10 = DECMode(9)

	SetModeMouseX10     = "\x1b[?9h"
	ResetModeMouseX10   = "\x1b[?9l"
	RequestModeMouseX10 = "\x1b[?9$p"
)

// Text Cursor Enable Mode (DECTCEM) is a mode that shows/hides the cursor.
//
// See: https://vt100.net/docs/vt510-rm/DECTCEM.html
const (
	ModeTextCursorEnable = DECMode(25)
	DECTCEM              = ModeTextCursorEnable

	SetModeTextCursorEnable     = "\x1b[?25h"
	ResetModeTextCursorEnable   = "\x1b[?25l"
	RequestModeTextCursorEnable = "\x1b[?25$p"
	SetModeDECTCEM              = SetModeTextCursorEnable
	ResetModeDECTCEM            = ResetModeTextCursorEnable
	RequestModeDECTCEM          = RequestModeTextCursorEnable
)

// Numeric Keypad Mode (DECNKM) is a mode that determines whether the keypad
// sends application sequences or numeric sequences.
//
// This works like DECKPAM and DECKPNM, but uses different sequences.
//
// See: https://vt100.net/docs/vt510-rm/DECNKM.html
const (
	ModeNumericKeypad = DECMode(66)
	DECNKM            = ModeNumericKeypad

	SetModeNumericKeypad     = "\x1b[?66h"
	ResetModeNumericKeypad   = "\x1b[?66l"
	RequestModeNumericKeypad = "\x1b[?66$p"
	SetModeDECNKM            = SetModeNumericKeypad
	ResetModeDECNKM          = ResetModeNumericKeypad
	RequestModeDECNKM        = RequestModeNumericKeypad
)

// Backarrow Key Mode (DECBKM) is a mode that determines whether the backspace
// key sends a backspace or delete character. Disabled by default.
//
// See: https://vt100.net/docs/vt510-rm/DECBKM.html
const (
	ModeBackarrowKey = DECMode(67)
	DECBKM           = ModeBackarrowKey

	SetModeBackarrowKey     = "\x1b[?67h"
	ResetModeBackarrowKey   = "\x1b[?67l"
	RequestModeBackarrowKey = "\x1b[?67$p"
	SetModeDECBKM           = SetModeBackarrowKey
	ResetModeDECBKM         = ResetModeBackarrowKey
	RequestModeDECBKM       = RequestModeBackarrowKey
)

// Left Right Margin Mode (DECLRMM) is a mode that determines whether the left
// and right margins can be set with DECSLRM.
//
// See: https://vt100.net/docs/vt510-rm/DECLRMM.html
const (
	ModeLeftRightMargin = DECMode(69)
	DECLRMM             = ModeLeftRightMargin

	SetModeLeftRightMargin     = "\x1b[?69h"
	ResetModeLeftRightMargin   = "\x1b[?69l"
	RequestModeLeftRightMargin = "\x1b[?69$p"
	SetModeDECLRMM             = SetModeLeftRightMargin
	ResetModeDECLRMM           = ResetModeLeftRightMargin
	RequestModeDECLRMM         = RequestModeLeftRightMargin
)

// Normal Mouse Mode is a mode that determines whether the mouse reports on
// button presses and releases. It will also report modifier keys, wheel
// events, and extra buttons.
//
// It uses the same encoding as ModeMouseX10 with a few differences.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking
const (
	ModeMouseNormal = DECMode(1000)

	SetModeMouseNormal     = "\x1b[?1000h"
	ResetModeMouseNormal   = "\x1b[?1000l"
	RequestModeMouseNormal = "\x1b[?1000$p"
)

// Highlight Mouse Tracking is a mode that determines whether the mouse reports
// on button presses, releases, and highlighted cells.
//
// It uses the same encoding as ModeMouseNormal with a few differences:
//
// On highlight events, the terminal responds with the following encoding:
//
// CSI t CxCy
// CSI T CxCyCxCyCxCy
//
// Where the parameters are startx, starty, endx, endy, mousex, and mousey.
const (
	ModeMouseHighlight = DECMode(1001)

	SetModeMouseHighlight     = "\x1b[?1001h"
	ResetModeMouseHighlight   = "\x1b[?1001l"
	RequestModeMouseHighlight = "\x1b[?1001$p"
)

// Button Event Mouse Tracking is essentially the same as ModeMouseNormal,
// but it also reports button-motion events when a button is pressed.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking
const (
	ModeMouseButtonEvent = DECMode(1002)

	SetModeMouseButtonEvent     = "\x1b[?1002h"
	ResetModeMouseButtonEvent   = "\x1b[?1002l"
	RequestModeMouseButtonEvent = "\x1b[?1002$p"
)

// Any Event Mouse Tracking is the same as ModeMouseButtonEvent, except that
// all motion events are reported even if no mouse buttons are pressed.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking
const (
	ModeMouseAnyEvent = DECMode(1003)

	SetModeMouseAnyEvent     = "\x1b[?1003h"
	ResetModeMouseAnyEvent   = "\x1b[?1003l"
	RequestModeMouseAnyEvent = "\x1b[?1003$p"
)

// Focus Event Mode is a mode that determines whether the terminal reports focus
// and blur events.
//
// The terminal sends the following encoding:
//
// CSI I // Focus In
// CSI O // Focus Out
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Focus-Tracking
const (
	ModeFocusEvent = DECMode(1004)

	SetModeFocusEvent     = "\x1b[?1004h"
	ResetModeFocusEvent   = "\x1b[?1004l"
	RequestModeFocusEvent = "\x1b[?1004$p"
)

// UTF-8 Extended Mouse Mode is a mode that changes the mouse tracking encoding
// to use UTF-8 parameters.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking
const (
	ModeMouseExtUtf8 = DECMode(1005)

	SetModeMouseExtUtf8     = "\x1b[?1005h"
	ResetModeMouseExtUtf8   = "\x1b[?1005l"
	RequestModeMouseExtUtf8 = "\x1b[?1005$p"
)

// SGR Extended Mouse Mode is a mode that changes the mouse tracking encoding
// to use SGR parameters.
//
// The terminal responds with the following encoding:
//
// CSI < Cb ; Cx ; Cy M
//
// Where Cb is the same as ModeMouseNormal, and Cx and Cy are the x and y.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking
const (
	ModeMouseExtSgr = DECMode(1006)

	SetModeMouseExtSgr     = "\x1b[?1006h"
	ResetModeMouseExtSgr   = "\x1b[?1006l"
	RequestModeMouseExtSgr = "\x1b[?1006$p"
)

// URXVT Extended Mouse Mode is a mode that changes the mouse tracking encoding
// to use an alternate encoding.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking
const (
	ModeMouseExtUrxvt = DECMode(1015)

	SetModeMouseExtUrxvt     = "\x1b[?1015h"
	ResetModeMouseExtUrxvt   = "\x1b[?1015l"
	RequestModeMouseExtUrxvt = "\x1b[?1015$p"
)

// SGR Pixel Extended Mouse Mode is a mode that changes the mouse tracking
// encoding to use SGR parameters with pixel coordinates.
//
// This is similar to ModeMouseExtSgr, but also reports pixel coordinates.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking
const (
	ModeMouseExtSgrPixel = DECMode(1016)

	SetModeMouseExtSgrPixel     = "\x1b[?1016h"
	ResetModeMouseExtSgrPixel   = "\x1b[?1016l"
	RequestModeMouseExtSgrPixel = "\x1b[?1016$p"
)

// Alternate Screen Mode is a mode that determines whether the alternate screen
// buffer is active. When this mode is enabled, the alternate screen buffer is
// cleared.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-The-Alternate-Screen-Buffer
const (
	ModeAltScreen = DECMode(1047)

	SetModeAltScreen     = "\x1b[?1047h"
	ResetModeAltScreen   = "\x1b[?1047l"
	RequestModeAltScreen = "\x1b[?1047$p"
)

// Save Cursor Mode is a mode that saves the cursor position.
// This is equivalent to SaveCursor and RestoreCursor.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-The-Alternate-Screen-Buffer
const (
	ModeSaveCursor = DECMode(1048)

	SetModeSaveCursor     = "\x1b[?1048h"
	ResetModeSaveCursor   = "\x1b[?1048l"
	RequestModeSaveCursor = "\x1b[?1048$p"
)

// Alternate Screen Save Cursor Mode is a mode that saves the cursor position as in
// ModeSaveCursor, switches to the alternate screen buffer as in ModeAltScreen,
// and clears the screen on switch.
//
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-The-Alternate-Screen-Buffer
const (
	ModeAltScreenSaveCursor = DECMode(1049)

	SetModeAltScreenSaveCursor     = "\x1b[?1049h"
	ResetModeAltScreenSaveCursor   = "\x1b[?1049l"
	RequestModeAltScreenSaveCursor = "\x1b[?1049$p"
)

// Bracketed Paste Mode is a mode that determines whether pasted text is
// bracketed with escape sequences.
//
// See: https://cirw.in/blog/bracketed-paste
// See: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Bracketed-Paste-Mode
const (
	ModeBracketedPaste = DECMode(2004)

	SetModeBracketedPaste     = "\x1b[?2004h"
	ResetModeBracketedPaste   = "\x1b[?2004l"
	RequestModeBracketedPaste = "\x1b[?2004$p"
)

// Synchronized Output Mode is a mode that determines whether output is
// synchronized with the terminal.
//
// See: https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036
const (
	ModeSynchronizedOutput = DECMode(2026)

	SetModeSynchronizedOutput     = "\x1b[?2026h"
	ResetModeSynchronizedOutput   = "\x1b[?2026l"
	RequestModeSynchronizedOutput = "\x1b[?2026$p"
)

// Unicode Core Mode is a mode that determines whether the terminal should use
// Unicode grapheme clustering to calculate the width of glyphs for each
// terminal cell.
//
// See: https://github.com/contour-terminal/terminal-unicode-core
const (
	ModeUnicodeCore = DECMode(2027)

	SetModeUnicodeCore     = "\x1b[?2027h"
	ResetModeUnicodeCore   = "\x1b[?2027l"
	RequestModeUnicodeCore = "\x1b[?2027$p"
)

// Light/Dark Mode is a mode that enables reporting the operating system's color
// scheme (light or dark) preference. It reports the color scheme as a DSR
// and LightDarkReport escape sequences encoded as follows:
//
// CSI ? 997 ; 1 n   for dark mode
// CSI ? 997 ; 2 n   for light mode
//
// The color preference can also be requested via the following DSR and
// RequestLightDarkReport escape sequences:
//
// CSI ? 996 n
//
// See: https://contour-terminal.org/vt-extensions/color-palette-update-notifications/
const (
	ModeLightDark = DECMode(2031)

	SetModeLightDark     = "\x1b[?2031h"
	ResetModeLightDark   = "\x1b[?2031l"
	RequestModeLightDark = "\x1b[?2031$p"
)

// In-Band Resize Mode is a mode that reports terminal resize events as escape
// sequences. This is useful for systems that do not support SIGWINCH like
// Windows.
//
// The terminal then sends the following encoding:
//
// CSI 48 ; cellsHeight ; cellsWidth ; pixelHeight ; pixelWidth t
//
// See: https://gist.github.com/rockorager/e695fb2924d36b2bcf1fff4a3704bd83
const (
	ModeInBandResize = DECMode(2048)

	SetModeInBandResize     = "\x1b[?2048h"
	ResetModeInBandResize   = "\x1b[?2048l"
	RequestModeInBandResize = "\x1b[?2048$p"
)

// Win32Input is a mode that determines whether input is processed by the
// Win32 console and Conpty.
//
// See: https://github.com/microsoft/terminal/blob/main/doc/specs/%234999%20-%20Improved%20keyboard%20handling%20in%20Conpty.md
const (
	ModeWin32Input = DECMode(9001)

	SetModeWin32Input     = "\x1b[?9001h"
	ResetModeWin32Input   = "\x1b[?9001l"
	RequestModeWin32Input = "\x1b[?9001$p"
)
