name: build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [~1.17, ^1]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Download Go modules
        run: go mod download
        working-directory: ./exp/teatest

      - name: Build
        run: go build -v ./...
        working-directory: ./exp/teatest

      - name: Test
        run: go test -v ./...
        working-directory: ./exp/teatest
